CC = g++
CFLAGS = -g -Wall
SRCS = main2.cpp
PROG = $(notdir $(CURDIR))

OPENCV = `pkg-config opencv --cflags --libs`
LASPICAM = -lraspicam -lraspicam_cv
LIBS = $(OPENCV) $(LASPICAM)
WIRINGPI = '-lwiringPi'
LOCATION = '/home/pi/wiringPi/wiringPi/softServo.c -Ihome/pi/wiringPi/wiringPi -lwiringPi'
.PHONY: all clean

$(PROG):$(SRCS)
	$(CC) $(CFLAGS) -o $(PROG) $(SRCS) $(LIBS) $(LOCATION)

all: $(PROG)

clean:
	rm -f $(OBJS) $(PROG)
